// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: post.proto

package com.vopher.javaprotobuf.model;

public final class PostProto {
  private PostProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PostOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Post)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string body = 3;</code>
     * @return The body.
     */
    java.lang.String getBody();
    /**
     * <code>string body = 3;</code>
     * @return The bytes for body.
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>repeated .Comment comment = 4;</code>
     */
    java.util.List<com.vopher.javaprotobuf.model.CommentProto.Comment> 
        getCommentList();
    /**
     * <code>repeated .Comment comment = 4;</code>
     */
    com.vopher.javaprotobuf.model.CommentProto.Comment getComment(int index);
    /**
     * <code>repeated .Comment comment = 4;</code>
     */
    int getCommentCount();
    /**
     * <code>repeated .Comment comment = 4;</code>
     */
    java.util.List<? extends com.vopher.javaprotobuf.model.CommentProto.CommentOrBuilder> 
        getCommentOrBuilderList();
    /**
     * <code>repeated .Comment comment = 4;</code>
     */
    com.vopher.javaprotobuf.model.CommentProto.CommentOrBuilder getCommentOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Post}
   */
  public static final class Post extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Post)
      PostOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Post.newBuilder() to construct.
    private Post(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Post() {
      title_ = "";
      body_ = "";
      comment_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Post();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Post(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                comment_ = new java.util.ArrayList<com.vopher.javaprotobuf.model.CommentProto.Comment>();
                mutable_bitField0_ |= 0x00000001;
              }
              comment_.add(
                  input.readMessage(com.vopher.javaprotobuf.model.CommentProto.Comment.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          comment_ = java.util.Collections.unmodifiableList(comment_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vopher.javaprotobuf.model.PostProto.internal_static_Post_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vopher.javaprotobuf.model.PostProto.internal_static_Post_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vopher.javaprotobuf.model.PostProto.Post.class, com.vopher.javaprotobuf.model.PostProto.Post.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 3;
    private volatile java.lang.Object body_;
    /**
     * <code>string body = 3;</code>
     * @return The body.
     */
    @java.lang.Override
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 3;</code>
     * @return The bytes for body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMENT_FIELD_NUMBER = 4;
    private java.util.List<com.vopher.javaprotobuf.model.CommentProto.Comment> comment_;
    /**
     * <code>repeated .Comment comment = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.vopher.javaprotobuf.model.CommentProto.Comment> getCommentList() {
      return comment_;
    }
    /**
     * <code>repeated .Comment comment = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.vopher.javaprotobuf.model.CommentProto.CommentOrBuilder> 
        getCommentOrBuilderList() {
      return comment_;
    }
    /**
     * <code>repeated .Comment comment = 4;</code>
     */
    @java.lang.Override
    public int getCommentCount() {
      return comment_.size();
    }
    /**
     * <code>repeated .Comment comment = 4;</code>
     */
    @java.lang.Override
    public com.vopher.javaprotobuf.model.CommentProto.Comment getComment(int index) {
      return comment_.get(index);
    }
    /**
     * <code>repeated .Comment comment = 4;</code>
     */
    @java.lang.Override
    public com.vopher.javaprotobuf.model.CommentProto.CommentOrBuilder getCommentOrBuilder(
        int index) {
      return comment_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, body_);
      }
      for (int i = 0; i < comment_.size(); i++) {
        output.writeMessage(4, comment_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, body_);
      }
      for (int i = 0; i < comment_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, comment_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.vopher.javaprotobuf.model.PostProto.Post)) {
        return super.equals(obj);
      }
      com.vopher.javaprotobuf.model.PostProto.Post other = (com.vopher.javaprotobuf.model.PostProto.Post) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!getCommentList()
          .equals(other.getCommentList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      if (getCommentCount() > 0) {
        hash = (37 * hash) + COMMENT_FIELD_NUMBER;
        hash = (53 * hash) + getCommentList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.vopher.javaprotobuf.model.PostProto.Post parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vopher.javaprotobuf.model.PostProto.Post parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vopher.javaprotobuf.model.PostProto.Post parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vopher.javaprotobuf.model.PostProto.Post parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vopher.javaprotobuf.model.PostProto.Post parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vopher.javaprotobuf.model.PostProto.Post parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vopher.javaprotobuf.model.PostProto.Post parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vopher.javaprotobuf.model.PostProto.Post parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vopher.javaprotobuf.model.PostProto.Post parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.vopher.javaprotobuf.model.PostProto.Post parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vopher.javaprotobuf.model.PostProto.Post parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vopher.javaprotobuf.model.PostProto.Post parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.vopher.javaprotobuf.model.PostProto.Post prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Post}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Post)
        com.vopher.javaprotobuf.model.PostProto.PostOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vopher.javaprotobuf.model.PostProto.internal_static_Post_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vopher.javaprotobuf.model.PostProto.internal_static_Post_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vopher.javaprotobuf.model.PostProto.Post.class, com.vopher.javaprotobuf.model.PostProto.Post.Builder.class);
      }

      // Construct using com.vopher.javaprotobuf.model.PostProto.Post.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCommentFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        title_ = "";

        body_ = "";

        if (commentBuilder_ == null) {
          comment_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          commentBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vopher.javaprotobuf.model.PostProto.internal_static_Post_descriptor;
      }

      @java.lang.Override
      public com.vopher.javaprotobuf.model.PostProto.Post getDefaultInstanceForType() {
        return com.vopher.javaprotobuf.model.PostProto.Post.getDefaultInstance();
      }

      @java.lang.Override
      public com.vopher.javaprotobuf.model.PostProto.Post build() {
        com.vopher.javaprotobuf.model.PostProto.Post result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.vopher.javaprotobuf.model.PostProto.Post buildPartial() {
        com.vopher.javaprotobuf.model.PostProto.Post result = new com.vopher.javaprotobuf.model.PostProto.Post(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.title_ = title_;
        result.body_ = body_;
        if (commentBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            comment_ = java.util.Collections.unmodifiableList(comment_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.comment_ = comment_;
        } else {
          result.comment_ = commentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vopher.javaprotobuf.model.PostProto.Post) {
          return mergeFrom((com.vopher.javaprotobuf.model.PostProto.Post)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vopher.javaprotobuf.model.PostProto.Post other) {
        if (other == com.vopher.javaprotobuf.model.PostProto.Post.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        if (commentBuilder_ == null) {
          if (!other.comment_.isEmpty()) {
            if (comment_.isEmpty()) {
              comment_ = other.comment_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCommentIsMutable();
              comment_.addAll(other.comment_);
            }
            onChanged();
          }
        } else {
          if (!other.comment_.isEmpty()) {
            if (commentBuilder_.isEmpty()) {
              commentBuilder_.dispose();
              commentBuilder_ = null;
              comment_ = other.comment_;
              bitField0_ = (bitField0_ & ~0x00000001);
              commentBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCommentFieldBuilder() : null;
            } else {
              commentBuilder_.addAllMessages(other.comment_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vopher.javaprotobuf.model.PostProto.Post parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vopher.javaprotobuf.model.PostProto.Post) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>string body = 3;</code>
       * @return The body.
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string body = 3;</code>
       * @return The bytes for body.
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 3;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 3;</code>
       * @param value The bytes for body to set.
       * @return This builder for chaining.
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.vopher.javaprotobuf.model.CommentProto.Comment> comment_ =
        java.util.Collections.emptyList();
      private void ensureCommentIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          comment_ = new java.util.ArrayList<com.vopher.javaprotobuf.model.CommentProto.Comment>(comment_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.vopher.javaprotobuf.model.CommentProto.Comment, com.vopher.javaprotobuf.model.CommentProto.Comment.Builder, com.vopher.javaprotobuf.model.CommentProto.CommentOrBuilder> commentBuilder_;

      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public java.util.List<com.vopher.javaprotobuf.model.CommentProto.Comment> getCommentList() {
        if (commentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(comment_);
        } else {
          return commentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public int getCommentCount() {
        if (commentBuilder_ == null) {
          return comment_.size();
        } else {
          return commentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public com.vopher.javaprotobuf.model.CommentProto.Comment getComment(int index) {
        if (commentBuilder_ == null) {
          return comment_.get(index);
        } else {
          return commentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public Builder setComment(
          int index, com.vopher.javaprotobuf.model.CommentProto.Comment value) {
        if (commentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommentIsMutable();
          comment_.set(index, value);
          onChanged();
        } else {
          commentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public Builder setComment(
          int index, com.vopher.javaprotobuf.model.CommentProto.Comment.Builder builderForValue) {
        if (commentBuilder_ == null) {
          ensureCommentIsMutable();
          comment_.set(index, builderForValue.build());
          onChanged();
        } else {
          commentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public Builder addComment(com.vopher.javaprotobuf.model.CommentProto.Comment value) {
        if (commentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommentIsMutable();
          comment_.add(value);
          onChanged();
        } else {
          commentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public Builder addComment(
          int index, com.vopher.javaprotobuf.model.CommentProto.Comment value) {
        if (commentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommentIsMutable();
          comment_.add(index, value);
          onChanged();
        } else {
          commentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public Builder addComment(
          com.vopher.javaprotobuf.model.CommentProto.Comment.Builder builderForValue) {
        if (commentBuilder_ == null) {
          ensureCommentIsMutable();
          comment_.add(builderForValue.build());
          onChanged();
        } else {
          commentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public Builder addComment(
          int index, com.vopher.javaprotobuf.model.CommentProto.Comment.Builder builderForValue) {
        if (commentBuilder_ == null) {
          ensureCommentIsMutable();
          comment_.add(index, builderForValue.build());
          onChanged();
        } else {
          commentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public Builder addAllComment(
          java.lang.Iterable<? extends com.vopher.javaprotobuf.model.CommentProto.Comment> values) {
        if (commentBuilder_ == null) {
          ensureCommentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, comment_);
          onChanged();
        } else {
          commentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public Builder clearComment() {
        if (commentBuilder_ == null) {
          comment_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          commentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public Builder removeComment(int index) {
        if (commentBuilder_ == null) {
          ensureCommentIsMutable();
          comment_.remove(index);
          onChanged();
        } else {
          commentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public com.vopher.javaprotobuf.model.CommentProto.Comment.Builder getCommentBuilder(
          int index) {
        return getCommentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public com.vopher.javaprotobuf.model.CommentProto.CommentOrBuilder getCommentOrBuilder(
          int index) {
        if (commentBuilder_ == null) {
          return comment_.get(index);  } else {
          return commentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public java.util.List<? extends com.vopher.javaprotobuf.model.CommentProto.CommentOrBuilder> 
           getCommentOrBuilderList() {
        if (commentBuilder_ != null) {
          return commentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(comment_);
        }
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public com.vopher.javaprotobuf.model.CommentProto.Comment.Builder addCommentBuilder() {
        return getCommentFieldBuilder().addBuilder(
            com.vopher.javaprotobuf.model.CommentProto.Comment.getDefaultInstance());
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public com.vopher.javaprotobuf.model.CommentProto.Comment.Builder addCommentBuilder(
          int index) {
        return getCommentFieldBuilder().addBuilder(
            index, com.vopher.javaprotobuf.model.CommentProto.Comment.getDefaultInstance());
      }
      /**
       * <code>repeated .Comment comment = 4;</code>
       */
      public java.util.List<com.vopher.javaprotobuf.model.CommentProto.Comment.Builder> 
           getCommentBuilderList() {
        return getCommentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.vopher.javaprotobuf.model.CommentProto.Comment, com.vopher.javaprotobuf.model.CommentProto.Comment.Builder, com.vopher.javaprotobuf.model.CommentProto.CommentOrBuilder> 
          getCommentFieldBuilder() {
        if (commentBuilder_ == null) {
          commentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.vopher.javaprotobuf.model.CommentProto.Comment, com.vopher.javaprotobuf.model.CommentProto.Comment.Builder, com.vopher.javaprotobuf.model.CommentProto.CommentOrBuilder>(
                  comment_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          comment_ = null;
        }
        return commentBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Post)
    }

    // @@protoc_insertion_point(class_scope:Post)
    private static final com.vopher.javaprotobuf.model.PostProto.Post DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.vopher.javaprotobuf.model.PostProto.Post();
    }

    public static com.vopher.javaprotobuf.model.PostProto.Post getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Post>
        PARSER = new com.google.protobuf.AbstractParser<Post>() {
      @java.lang.Override
      public Post parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Post(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Post> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Post> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.vopher.javaprotobuf.model.PostProto.Post getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Post_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Post_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\npost.proto\032\rcomment.proto\"J\n\004Post\022\n\n\002i" +
      "d\030\001 \001(\005\022\r\n\005title\030\002 \001(\t\022\014\n\004body\030\003 \001(\t\022\031\n\007" +
      "comment\030\004 \003(\0132\010.CommentB*\n\035com.vopher.ja" +
      "vaprotobuf.modelB\tPostProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.vopher.javaprotobuf.model.CommentProto.getDescriptor(),
        });
    internal_static_Post_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Post_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Post_descriptor,
        new java.lang.String[] { "Id", "Title", "Body", "Comment", });
    com.vopher.javaprotobuf.model.CommentProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
